# Dependencies
markdown_ext:     md
# pygments:         true
highlighter:     rougue

# Permalinks
permalink:        pretty

# Setup
title:           ike 
tagline:         'You must be here with purpose'
description:     'Pieces of information that Iļja Ketris shares with the world.'
url:              http://punund.github.io

author:
  name:           'Iļja Ketris'
  url:            https://github.com/punund


# Custom vars
version:          2.0.0

github:
